### ISSUE TITLE
Unable to resolve module 'crypto' as module does not exist in module map

### ISSUE THREAD

**Issue by kevinlu1211** [auth0/node-jsonwebtoken#407] opened 2017-09-27 17:00 UTC
So I just did `yarn add jsonwebtoken` and I first got an error:

`Unable to resolve module stream` so then I install it via `yarn add stream`. 

Then the next problem is:

`Unable to resolve util` so then in install it via `yarn add util

Then the next problem is:

`Unable to resolve net` so again I add it `yarn add net` 

Then finally I come to 

`Unable to resolve crypto` but when I add it I get this error:

```
warning crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
```

And regardless of how I try to install it, I get stuck here. Any ideas?

**Comment by joovel** [comment] 2017-09-27 18:45
What's in your `package.json`? A clean install works fine; perhaps you have outdated dependencies?

```
$ yarn --version
1.1.0
$ yarn add jsonwebtoken
yarn add v1.1.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 16 new dependencies.
├─ base64url@2.0.0
├─ buffer-equal-constant-time@1.0.1
├─ ecdsa-sig-formatter@1.0.9
├─ jsonwebtoken@8.0.1
├─ jwa@1.1.5
├─ jws@3.1.4
├─ lodash.includes@4.3.0
├─ lodash.isboolean@3.0.3
├─ lodash.isinteger@4.0.4
├─ lodash.isnumber@3.0.3
├─ lodash.isplainobject@4.0.6
├─ lodash.isstring@4.0.1
├─ lodash.once@4.1.1
├─ ms@2.0.0
├─ safe-buffer@5.1.1
└─ xtend@4.0.1
✨  Done in 0.71s.
```

**Comment by kevinlu1211** [comment] 2017-09-27 22:56
Here are my dependencies:

```
"dependencies": {
    "add-graphql-subscriptions": "^1.0.1",
    "emoji-aware": "^3.0.1",
    "eventemitter3": "^2.0.3",
    "hoist-non-react-statics": "^2.3.1",
    "jsonwebtoken": "^8.0.1",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "prismic-javascript": "1.3.0",
    "react": "16.0.0-alpha.12",
    "react-apollo": "^1.4.14",
    "react-native": "0.47.1",
    "react-native-action-button": "^2.8.0",
    "react-native-auth0": "^1.2.0",
    "react-native-htmlview": "^0.12.0",
    "react-native-vector-icons": "^4.3.0",
    "react-navigation": "^1.0.0-beta.11",
    "subscriptions-transport-ws": "^0.8.3"
  }
```
Yes I can install everything fine, it's when I do something like `jwt = require('jsonwebtoken')` it fails

**Comment by joovel** [comment] 2017-09-28 00:03
This module does not support react-native because it requires node-jws which requires streams.  See also issue #355 .

**Comment by joovel** [comment] 2017-09-28 00:05
@ziluvatar Recommending closing as a duplicate of #355 .

**Comment by ziluvatar** [comment] 2017-09-29 10:21
Thanks @joovel for the investigation and the contribution you have made lately, awesome.

@kevinlu1211 if you find out the root problem with react-native, please post it, even if this is a NodeJS library, it would be good for other people to make it work with react-native.

**Closed** 2017-09-29 10:21 UTC

**Comment by GaneshSaiKumar** [comment] 2019-01-02 04:52
@kevinlu1211 @ziluvatar 
Have you guys found the root solution?
I'm still facing the problem
