### ISSUE TITLE
Extra Padding

### ISSUE THREAD

**Issue by clozr** [auth0/node-jsonwebtoken#297] opened 2017-01-17 19:56 UTC
I am trying to use jsonwebtoken with react-native. In debug version, everything is fine. However when I create a release bundle, I am getting extra padding which is failing the verification at the server side. 
Here is the difference in debug version and release version signatures:
9qKUuvNSO_VU3B7g2H-lHrt18HRZV4TQN2ZLbdkpVbQ ( debug)
9qKUuvNSO_VU3B7g2H-lHrt18HRZV4TQN2ZLbdkpVbQ**VbQAAAAA** (release)

Any ideas why this may be happening?

**Comment by ziluvatar** [comment] 2017-02-06 22:26
@clozr did you manage to figure out what happened? 
Can you reproduce it with an example of payload and secret you could share here?

**Comment by markandrus** [comment] 2017-04-10 19:25
@clozr any chance your release process uses Browserify? I had a very similar issue, in Firefox, specifically. I expect it had to with the version of `buffer` Browserify was bundling for the browser. Sorry I cannot provide further details.

**Comment by ziluvatar** [comment] 2017-07-13 17:27
Closing. @clozr if you still have the issue or you solved it and you want to share what happened it be free to open or comment even if the issue is closed.

**Closed by ziluvatar** 2017-07-13 17:27 UTC
Labels: question
