### ISSUE TITLE
Support promise, async/await for some important actions like sign, verify jwt.

### ISSUE THREAD

**Issue by mattnguyengit** [auth0/node-jsonwebtoken#736] opened 2020-08-05 14:31 UTC
### Describe the problem you'd like to have solved

> I usually use **sign, verify function** for my authentication process by synchronous syntax. I don't know the process is heavy or not but better to use asynchronous for it.

> In documentation, I see we have callback syntax but it is not popular on modern code these days.

**Comment by panva** [comment] 2020-08-05 15:28
Duplicate of #111

**Closed by panva** 2020-08-05 15:28 UTC
